feat: Datepicker & Date-time picker
kyndryl-design-system/web-components pull request #12
Opened 2023-09-07 07:02 UTC by maulik-thaker1

## Summary

Datepicker component with two variants : Datepicker and date with time picker

## ADO Story 

https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1238186

## Checklist

- [ ] Used Conventional Commit messages as outlined in the contributing guide.
  - [ ] Noted breaking changes (if any).
- [ ] Documented/updated all props, events, slots, parts, etc with JSDoc.
  - [ ] Ran the `analyze` command to update Storybook docs.
- [ ] Added/updated Stories with controls to cover all variants.
- [ ] Added/updated a basic unit test, at least, for each component.
- [ ] Added/updated the Figma link for the Story's Design tab.
- [ ] Added any new component exports to the src/index.ts file

2023-09-07 14:16 UTC, brian-patrick-3 requested changes
Seems pretty good! I did notice one thing that seems weird: when I type in the field it removes focus entirely, which doesn't seem right when I compare to a simple `<input type="date">`.

2023-09-07 14:16 UTC, brian-patrick-3 commented on src/components/reusable/datePicker/datepicker.scss
> +}
I don't think this is used?

2023-09-07 15:42 UTC, brian-patrick-3 commented
> focus stays when type by keyboard or arrow up / down

Only after there's already an entry. The first time I try to type when it's empty, it loses focus.

2023-09-07 15:44 UTC, maulik-thaker1 commented on src/components/reusable/datePicker/datepicker.scss
> +}
done

2023-09-07 15:55 UTC, maulik-thaker1 commented
> > focus stays when type by keyboard or arrow up / down
> 
> Only after there's already an entry. The first time I try to type when it's empty, it loses focus.

yeah its weird don't know whats happen there. Can you help me out here. Think updating component on-input cause this issue might be.

2023-09-07 15:59 UTC, maulik-thaker1 commented
> > yeah its weird don't know whats happen there. Can you help me out here. Think updating component on-input cause this issue might be.
> 
> I don't have time to dig into it, but it might be related to setting inputEl.value on updated. Try taking that out.

sure I am looking into it.

2023-09-07 16:00 UTC, maulik-thaker1 commented
> > > yeah its weird don't know whats happen there. Can you help me out here. Think updating component on-input cause this issue might be.
> > 
> > 
> > I don't have time to dig into it, but it might be related to setting inputEl.value on updated. Try taking that out.
> 
> sure I am looking into it. why we need inputEl.value here. Can we remove for type="date"

2023-09-07 17:52 UTC, maulik-thaker1 commented
> > > yeah its weird don't know whats happen there. Can you help me out here. Think updating component on-input cause this issue might be.
> > 
> > 
> > I don't have time to dig into it, but it might be related to setting inputEl.value on updated. Try taking that out.
> 
> sure I am looking into it. but removing inputEl.value not worked.

I tried looking all possibilities but not sure why its losing focus. Need to deep digger may be something happened about LIT component update lifecycle but its not blocking anything.

2023-09-07 18:33 UTC, brian-patrick-3 approved these changes

2023-09-07 18:41 UTC, merged

2023-09-07 18:51 UTC, frodesigns commented
:tada: This PR is included in version 1.0.0-beta.51 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@kyndryl-design-system/web-components/v/1.0.0-beta.51)
- [GitHub release](https://github.com/kyndryl-design-system/web-components/releases/tag/v1.0.0-beta.51)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-11-13 15:04 UTC, brian-patrick-3 commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@kyndryl-design-system/shidoka-applications/v/1.0.0)
- [GitHub release](https://github.com/kyndryl-design-system/shidoka-applications/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: